### ISSUE TITLE
Project is empty!

### ISSUE THREAD

**Issue by doches** [ricohapi/theta-plugin-camera-api-sample-x#1]
The equivalent to this sample for the Theta Z1 (https://github.com/ricohapi/theta-plugin-camera-api-sample) was invaluable in documenting how to develop plugins for the previous generation of Ricoh cameras. When will this sample be available, so we can start updating existing plugins to work on the Theta X as well?

**Comment by DaisukeHohjoh** [comment]
>When will this sample be available,

Today RICOH pushed the code as v1.0.0. This project is sample code using Camera API for THETA X. I am sorry to have kept you waiting.

>so we can start updating existing plugins to work on the Theta X as well?

THETA X provides theta360.hardware.Camera & theta360.media.MediaRecorder classes to support 360 camera related features, not via android.hardware.Camera & android.media.MediaRecorder classes. This is very different point between THETA X and V/Z1 's API design. If you want to support THETA V/Z1/X 's Camera API as single plug-in APK, you need to switch using packages based on THETA model.

Actually Plug-in Library (https://github.com/ricohapi/theta-plugin-library) (v3.0.2 or later) supports a wrapper class to do it, RICOH have a plan to update original Camera API Sample project (https://github.com/ricohapi/theta-plugin-camera-api-sample) to show how to use the class.

**Comment by DaisukeHohjoh** [comment]
> Actually Plug-in Library (https://github.com/ricohapi/theta-plugin-library) (v3.0.2 or later) supports a wrapper class to do it, RICOH have a plan to update original Camera API Sample project (https://github.com/ricohapi/theta-plugin-camera-api-sample) to show how to use the class.

Today we updated original Camera API Sample project here.
https://github.com/ricohapi/theta-plugin-camera-api-sample
